# Site settings
title: "{ Magnus }"
email: m.brantheim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mostly adequate thoughts on programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  m-brantheim

# Build settings
markdown: kramdown
